[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
hello_world = "2NV1iSwqoG8iKpCSQEyG2e2je46djm8jr9KqYnLgwt5z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/hello-world.ts"
